import JSZip from 'jszip';
import fs from 'fs';
const buf = fs.readFileSync('/app/templates/timbrado.docx');
const z = await JSZip.loadAsync(buf);
const relsXml = await z.file('word/_rels/document.xml.rels').async('string');
const updatedRels = relsXml.replace('</Relationships>', '<Relationship Id="rIdSejuscBg" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image3.png"/></Relationships>');
z.file('word/_rels/document.xml.rels', updatedRels);
const origXml = await z.file('word/document.xml').async('string');
const m = origXml.match(/<w:sectPr[\s\S]*?<\/w:sectPr>/);
const sectPr = m ? m[0].replace(/="([\d]+\.[\d]+)"/g, (_, v) => '="' + Math.round(parseFloat(v)) + '"') : '';
const docOpen = origXml.match(/(<w:document[\s\S]*?>)/)[1];
const bg = '<w:p><w:pPr><w:spacing w:before="0" w:after="0"/></w:pPr><w:r><w:drawing><wp:anchor behindDoc="1" simplePos="0" relativeHeight="1" locked="1" layoutInCell="1" allowOverlap="1" distT="0" distB="0" distL="0" distR="0"><wp:simplePos x="0" y="0"/><wp:positionH relativeFrom="page"><wp:posOffset>0</wp:posOffset></wp:positionH><wp:positionV relativeFrom="page"><wp:posOffset>0</wp:posOffset></wp:positionV><wp:extent cx="7575111" cy="10708323"/><wp:effectExtent b="0" l="0" r="0" t="0"/><wp:wrapNone/><wp:docPr id="9001" name="BG"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="BG"/><pic:cNvPicPr preferRelativeResize="0"/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rIdSejuscBg"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="7575111" cy="10708323"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:anchor></w:drawing></w:r></w:p>';
const newXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' + docOpen + '\n<w:body>\n' + bg + '\n<w:p><w:r><w:t>Teste de timbrado</w:t></w:r></w:p>\n' + sectPr + '\n</w:body>\n</w:document>';
z.file('word/document.xml', newXml);
const out = await z.generateAsync({type:'nodebuffer', compression:'DEFLATE'});
fs.writeFileSync('/app/verify_out.docx', out);
const z2 = await JSZip.loadAsync(out);
const rels2 = await z2.file('word/_rels/document.xml.rels').async('string');
const doc2 = await z2.file('word/document.xml').async('string');
console.log('rIdSejuscBg in rels:', rels2.includes('rIdSejuscBg'));
console.log('behindDoc=1 in body:', doc2.includes('behindDoc="1"'));
console.log('rIdSejuscBg in body:', doc2.includes('rIdSejuscBg'));
console.log('image3 in zip:', !!z2.file('word/media/image3.png'));
console.log('OK - size:', out.length, 'bytes');
