-- AlterTable: add new values to OsTipo enum
ALTER TABLE `WorkOrder` MODIFY `tipo` ENUM('VISITA_TECNICA', 'TROCA_EQUIPAMENTO', 'ENTREGA', 'MANUTENCAO_REDE', 'MANUTENCAO_CAMERA', 'RECOLHIMENTO_EQUIPAMENTO', 'ACAO', 'OUTRO') NOT NULL;
