-- Adiciona o valor CANCELADO ao enum TicketStatus
-- MODIFY COLUMN em MySQL reconstrói a linha mas é seguro (sem IF NOT EXISTS necessário)
ALTER TABLE `Ticket` MODIFY COLUMN `status` ENUM('OPEN','VIEWED','EN_ROUTE','IN_SERVICE','COMPLETED','CANCELADO') NOT NULL DEFAULT 'OPEN';
ALTER TABLE `TicketHistory` MODIFY COLUMN `fromStatus` ENUM('OPEN','VIEWED','EN_ROUTE','IN_SERVICE','COMPLETED','CANCELADO');
ALTER TABLE `TicketHistory` MODIFY COLUMN `toStatus` ENUM('OPEN','VIEWED','EN_ROUTE','IN_SERVICE','COMPLETED','CANCELADO') NOT NULL;
